version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: client
    environment:
      - DOCKER_CONTAINER_HOST=http://server:5000
    restart: always
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: server
    environment:
      - ASPNETCORE_URLS=http://+:5000
